### ISSUE TITLE
Convert Class Files to Jasm

### ISSUE THREAD

**Issue by numeralnathan** [roscopeco/jasm#19]
Please create a tool to convert .class files into .jasm files.  This will make reading .class files much easier than the output from javap.

**Comment by Ristovski** [comment]
I wonder if having a disassembler would allow using `jasm` for patching Android apps. Given you can already convert `dex` files to `jar` (with the conveniently named `dex2jar` tool), this might open the door for an alternative to patching `smali` code (via `baksmali`).

**Comment by MikeAndrson** [comment]
> I wonder if having a disassembler would allow using `jasm` for patching Android apps. Given you can already convert `dex` files to `jar` (with the conveniently named `dex2jar` tool), this might open the door for an alternative to patching `smali` code (via `baksmali`).

`dex2jar` is a very old, kinda unmaintained tool with no support for newest DEX versions, translating debug info, handling weird edge cases etc. (see [here](https://github.com/Storyyeller/enjarify#why-not-dex2jar)) So I would NOT see it as a valid replacement/alternative to `baksmali`/`smali`. 

It's still good for some cases obviously, but I wouldn't use it for a full roundtrip (`dex` -> `jar` -> `dex`) on an average app and expect it to work.

**Comment by roscopeco** [comment]
This is now available in `develop`. To disassemble a `.class` file `src/com/example/MyClass.class` to the `src` directory with the command-line tool, you can now do e.g:

`jasm -d -i classes -o src com/example/MyClass.class`

Scheduled for 0.6.0 release this weekend.

**Comment by numeralnathan** [comment]
@roscopeco Awesome!  Thank you!
