### ISSUE TITLE
Error running README.md example

### ISSUE THREAD

**Issue by neomafo88** [roscopeco/jasm#20]
```
public class com/example/HelloWorld {
  public static main([java/lang/String)V {
    getstatic java/lang/System.out
    ldc "Hello, World"
    invokevirtual java/io/PrintStream.println(java/lang/String)V
    return
  }
}
```

Error Message

> Index 0 out of bounds for length 0

I suspect the error is on the `getstatic java/lang/System.out` line, due to the missing import.
How do I write `import java.lang.*;` in JASM?

**Comment by neomafo88** [comment]
Nvm, realised it was just missing a parameter, i.e.

```
public class com/example/HelloWorld {
  public static main([java/lang/String)V {
    getstatic java/lang/System.out java/io/PrintStream
    ldc "Hello, World!"
    invokevirtual java/io/PrintStream.println(java/lang/String)V
    return
  }
}
```

**Comment by roscopeco** [comment]
Thanks for reporting this! Reopening as I want to fix the README, and also make sure this case gives a more descriptive error message.
