### ISSUE TITLE
Annotations?

### ISSUE THREAD

**Issue by MattiDragon** [roscopeco/jasm#34]
There doesn't currently seem to be any way to apply annotation to things is jasm files. Some frameworks and libraries depend on runtime annotations and would thus require class files intended for use with them to have it. 

If this is a feature then examples of the syntax would be useful

**Comment by roscopeco** [comment]
Thanks for this :) 

Unfortunately annotations aren't currently supported, but coincidentally I started working on them yesterday. They'll be in the next release.

**Comment by MattiDragon** [comment]
Any progress?

**Comment by roscopeco** [comment]
> Any progress?

Still a work-in-progress, the time I initially set aside for this was soaked up by https://github.com/roscopeco/jasm/issues/35 and I've been a bit pressed for OSS time otherwise. This is still top of the list though, I hope to have something ready soon!

**Comment by roscopeco** [comment]
Apologies for the delay on this @MattiDragon , work and life got in the way. Annotations are now supported in the assembler in the develop branch. I just need to add support into the disassembler and then they can go into a release 🥳

See https://github.com/roscopeco/jasm/blob/develop/docs/examples.md#annotations for example syntax if you want to try them out 👍

**Comment by roscopeco** [comment]
Complete, annotations are now fully supported in `develop` and will be in the next release.
